sequenceDiagram
    participant Client
    participant portunus
    participant Door
    participant Application
    Application->>Door: Create /var/run/app.door
    portunus->>Door: Open
    portunus->>portunus: listen on port 80
    loop Handle Requests
        Client->>+portunus: Send HTTP Request
        portunus->>portunus: filter / decrypt request
        portunus->>+Application: Forward request via door_call
        Application->>-portunus: Send response via door_return
        portunus->>portunus: (optionally) encrypt response
        portunus->>-Client: Send HTTP Response
    end
