sequenceDiagram
    participant Client
    participant relaydoors
    participant Door
    participant Application
    Application->>Door: Create /var/run/app.door
    relaydoors->>Door: Open
    relaydoors->>relaydoors: listen on port 80
    loop Handle Requests
        Client->>+relaydoors: Send HTTP Request
        relaydoors->>relaydoors: filter / decrypt request
        relaydoors->>+Application: Forward request via door_call
        Application->>-relaydoors: Send response via door_return
        relaydoors->>relaydoors: (optionally) encrypt response
        relaydoors->>-Client: Send HTTP Response
    end
